spring.application.name=DAO
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#spring.sql.init.mode=always
#spring.sql.init.continue-on-error=false

spring.liquibase.enabled=true
#spring.liquibase.default-schema=demojoin
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
